apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message
spec:
  selector:
    matchLabels:
      app: log-message
  template:
    metadata:
      labels:
        app: log-message
    spec:
      containers:
      - name: log-message
        image: docker.pkg.github.com/usepe/log-message/log-message:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
