apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-message
  template:
    metadata:
      labels:
        app: post-message
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: post-message
        image: docker.pkg.github.com/usepe/post-message/post-message:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
